

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData  V3                                     /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

    
  $data.Entity.extend('NORTHWNDModel.Category', {
     'CategoryID': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CategoryName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':15 },
     'Description': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
     'Picture': { 'type':'Edm.Binary','maxLength':Number.POSITIVE_INFINITY },
     'Products': { 'type':'Array','elementType':'NORTHWNDModel.Product','inverseProperty':'Category' }
  });

  $data.Entity.extend('NORTHWNDModel.Product', {
     'ProductID': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'ProductName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'SupplierID': { 'type':'Edm.Int32' },
     'CategoryID': { 'type':'Edm.Int32' },
     'QuantityPerUnit': { 'type':'Edm.String','maxLength':20 },
     'UnitPrice': { 'type':'Edm.Decimal' },
     'UnitsInStock': { 'type':'Edm.Int16' },
     'UnitsOnOrder': { 'type':'Edm.Int16' },
     'ReorderLevel': { 'type':'Edm.Int16' },
     'Discontinued': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Category': { 'type':'NORTHWNDModel.Category','inverseProperty':'Products' },
     'Supplier': { 'type':'NORTHWNDModel.Supplier','inverseProperty':'Products' }
  });

  $data.Entity.extend('NORTHWNDModel.Supplier', {
     'SupplierID': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CompanyName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'ContactName': { 'type':'Edm.String','maxLength':30 },
     'ContactTitle': { 'type':'Edm.String','maxLength':30 },
     'Address': { 'type':'Edm.String','maxLength':60 },
     'City': { 'type':'Edm.String','maxLength':15 },
     'Region': { 'type':'Edm.String','maxLength':15 },
     'PostalCode': { 'type':'Edm.String','maxLength':10 },
     'Country': { 'type':'Edm.String','maxLength':15 },
     'Phone': { 'type':'Edm.String','maxLength':24 },
     'Fax': { 'type':'Edm.String','maxLength':24 },
     'HomePage': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
     'Products': { 'type':'Array','elementType':'NORTHWNDModel.Product','inverseProperty':'Supplier' }
  });

  $data.EntityContext.extend('DataService.NORTHWND', {
     'Categories': { type: $data.EntitySet, elementType: NORTHWNDModel.Category},
     'Products': { type: $data.EntitySet, elementType: NORTHWNDModel.Product},
     'Suppliers': { type: $data.EntitySet, elementType: NORTHWNDModel.Supplier}
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(DataService.NORTHWND);
  
      
})(window, $data);
      
    